import { Controller, Get, Param } from '@nestjs/common';
import { SearchService } from './search.service';
import { ApiHeader, ApiResponse, ApiTags } from '@nestjs/swagger';
import { Auth } from '../auth/auth.decorator';
import { AuthGuardsEnum } from '../../enums/authGuards.enum';
import { FindAllLtRo } from './ro/find-all-lt.ro';
import { FindAllEnRo } from './ro/find-all-en.ro';
import { ParentRo } from './ro/parent.ro';
import { ChildRo } from './ro/child.ro';

@ApiTags('search')
@Controller('api/v1/search')
export class SearchController {
  constructor(private readonly searchService: SearchService) {}

  @Get('parameters/lt')
  @ApiHeader({ required: true, name: 'project-id' })
  @ApiResponse({ status: 200, type: FindAllLtRo })
  @Auth(AuthGuardsEnum.CUSTOMER_PROJECT)
  async findAllLt(): Promise<FindAllLtRo> {
    return {
      items: [
        {
          name: 'carMark',
          title: 'Automobilio markė',
          items: [
            'Alfa Romeo',
            'Aston Martin',
            'Audi',
            'Bentley',
            'BMW',
            'Ferrari',
            'Ford',
            'Jaguar',
            'Jeep',
            'Land Rover',
            'Lexus',
            'Maserati',
            'Maybach',
            'Mercedes Benz',
            'Mini',
            'Porsche',
            'Rolls Royce',
            'Skoda',
            'Tesla',
            'Toyota',
            'Volkswagen',
            'Volvo',
          ],
        },
        {
          name: 'carModel',
          title: 'Automobilio modelis',
          items: [
            'Alfa Romeo Giulia',
            'STELVIO',
            'STELVIO QUADRIFOGLIO',
            'DBX',
            'VANTAGE',
            'DB11',
            'DBS',
            'Aston Martin Valkyrie',
            'A3',
            'S3',
            'RS3',
            'A4',
            'S4',
            'RS4',
            'A5',
            'S5',
            'RS5',
            'A6',
            'S6',
            'RS6',
            'A7',
            'S7',
            'RS7',
            'A8',
            'S8',
            'Q3',
            'RS Q3',
            'Q4',
            'Q5',
            'SQ5',
            'RS Q5',
            'Q7',
            'SQ8',
            'RS Q8',
            'TT',
            'TT S',
            'TT RS',
            'e-tron',
            'e-tron GT',
            'R8',
            'CONTINENTAL GT SPEED',
            'BENTAYGA',
            'FLYING SPUR',
            'CONTINENTAL GT',
            '2',
            '3',
            '4',
            '5',
            '6',
            '7',
            '8',
            'X3',
            'iX',
            'X4',
            'X5',
            'X6',
            'X7',
            'Z4',
            'M3',
            'M4',
            'M5',
            'M8',
            'X3M',
            'X4M',
            'X5M',
            'X6M',
            'i3',
            '812 Superfast',
            '812 GTS',
            '296 GTB',
            'SF90 Stradale',
            'SF90 Spider',
            'F8 Tributo',
            'F8 Spider',
            'Ferrari Roma',
            'Ferrari Portofino M',
            'MONZA SP1',
            'MONZA SP2',
            'Fiesta ST',
            'Fiesta RS',
            'Focus ST',
            'Focus RS',
            'Mustang',
            'GT',
            'F-Pace',
            'F-Type',
            'E-Pace',
            'XE',
            'I-Pace',
            'Gladiator',
            'Renegade',
            'Wrangler Unlimited Sahara',
            'Wrangler Unlimited Rubicon',
            'VELAR',
            'EVOQUE',
            'RANGE ROVER',
            'RANGE ROVER SPORT',
            'DISCOVERY',
            'DEFENDER',
            'UX',
            'NX',
            'ES',
            'RX',
            'LC',
            'LS',
            'RS F',
            'Levante',
            'Ghibli',
            'Quattroporte',
            'MC20',
            'GLS',
            'S',
            'EQS',
            'C',
            'CLA',
            'CLS',
            'E',
            'EQ',
            'G',
            'GLA',
            'GLE',
            'GLS',
            'S',
            'SL',
            'SLC',
            'V',
            'AMG GT Coupe',
            'AMG GT Roadster',
            'AMG GT 4-Door',
            'MINI',
            'MINI 4-Door',
            'MINI Cabrio',
            'CLUBMAN',
            'COUNTRYMAN',
            'MINI JOHN COOPER WORKS',
            '718 Boxster',
            '718 Cayman',
            '911',
            '911 Cabriolet',
            '911 Targa',
            '911 Turbo',
            '911 Turbo Cabriolet',
            '911 Turbo S',
            '911 Turbo S Cabriolet',
            'Taycan',
            'Taycan Cross Turismo',
            'Panamera',
            'Panamera Turbo S',
            'Macan',
            'Cayenne',
            'PHANTOM',
            'PHANTOM EXTENDED',
            'CULLINAN',
            'GHOST',
            'GHOST EXTENDED',
            'WRAITH',
            'DAWN',
            'Fabia',
            'Scala',
            'Octavia',
            'Superb',
            'Kamiq',
            'Karoq',
            'Kodiaq',
            'Enyaq iV',
            'Model S',
            'Model 3',
            'Model X',
            'Model Y',
            'Yaris',
            'GR Yaris',
            'Yaris Cross',
            'Corolla',
            'CH-R',
            'Camry',
            'GR Supra',
            'Prius',
            'Mirai',
            'RAV4',
            'Highlinder',
            'Land Cruiser',
            'Hilux',
            'Golf',
            'Golf Variant',
            'Passat',
            'Passat Alltrack',
            'T-cross',
            'Taigo',
            'T-Roc',
            'Tiguan',
            'Touareg',
            'Arteon',
            'ID3',
            'ID4',
            'Caddy',
            'XC40',
            'XC60',
            'XC90',
            'V60',
            'S90',
            'S60',
            'V90',
            'V60',
          ],
        },
        {
          name: 'year',
          title: 'Metai',
          items: [
            '2012',
            '2013',
            '2014',
            '2015',
            '2016',
            '2017',
            '2018',
            '2019',
            '2020',
            '2021',
          ],
        },
      ],
    };
  }

  @Get('parameters/en')
  @ApiHeader({ required: true, name: 'project-id' })
  @ApiResponse({ status: 200, type: FindAllEnRo })
  @Auth(AuthGuardsEnum.CUSTOMER_PROJECT)
  async findAllEn(): Promise<FindAllEnRo> {
    return {
      items: [
        {
          name: 'carMark',
          title: 'Automobilio markė',
          items: [
            'Alfa Romeo',
            'Aston Martin',
            'Audi',
            'Bentley',
            'BMW',
            'Ferrari',
            'Ford',
            'Jaguar',
            'Jeep',
            'Land Rover',
            'Lexus',
            'Maserati',
            'Maybach',
            'Mercedes Benz',
            'Mini',
            'Porsche',
            'Rolls Royce',
            'Skoda',
            'Tesla',
            'Toyota',
            'Volkswagen',
            'Volvo',
          ],
        },
        {
          name: 'carModel',
          title: 'Automobilio modelis',
          items: [
            'Alfa Romeo Giulia',
            'STELVIO',
            'STELVIO QUADRIFOGLIO',
            'DBX',
            'VANTAGE',
            'DB11',
            'DBS',
            'Aston Martin Valkyrie',
            'A3',
            'S3',
            'RS3',
            'A4',
            'S4',
            'RS4',
            'A5',
            'S5',
            'RS5',
            'A6',
            'S6',
            'RS6',
            'A7',
            'S7',
            'RS7',
            'A8',
            'S8',
            'Q3',
            'RS Q3',
            'Q4',
            'Q5',
            'SQ5',
            'RS Q5',
            'Q7',
            'SQ8',
            'RS Q8',
            'TT',
            'TT S',
            'TT RS',
            'e-tron',
            'e-tron GT',
            'R8',
            'CONTINENTAL GT SPEED',
            'BENTAYGA',
            'FLYING SPUR',
            'CONTINENTAL GT',
            '2',
            '3',
            '4',
            '5',
            '6',
            '7',
            '8',
            'X3',
            'iX',
            'X4',
            'X5',
            'X6',
            'X7',
            'Z4',
            'M3',
            'M4',
            'M5',
            'M8',
            'X3M',
            'X4M',
            'X5M',
            'X6M',
            'i3',
            '812 Superfast',
            '812 GTS',
            '296 GTB',
            'SF90 Stradale',
            'SF90 Spider',
            'F8 Tributo',
            'F8 Spider',
            'Ferrari Roma',
            'Ferrari Portofino M',
            'MONZA SP1',
            'MONZA SP2',
            'Fiesta ST',
            'Fiesta RS',
            'Focus ST',
            'Focus RS',
            'Mustang',
            'GT',
            'F-Pace',
            'F-Type',
            'E-Pace',
            'XE',
            'I-Pace',
            'Gladiator',
            'Renegade',
            'Wrangler Unlimited Sahara',
            'Wrangler Unlimited Rubicon',
            'VELAR',
            'EVOQUE',
            'RANGE ROVER',
            'RANGE ROVER SPORT',
            'DISCOVERY',
            'DEFENDER',
            'UX',
            'NX',
            'ES',
            'RX',
            'LC',
            'LS',
            'RS F',
            'Levante',
            'Ghibli',
            'Quattroporte',
            'MC20',
            'GLS',
            'S',
            'EQS',
            'C',
            'CLA',
            'CLS',
            'E',
            'EQ',
            'G',
            'GLA',
            'GLE',
            'GLS',
            'S',
            'SL',
            'SLC',
            'V',
            'AMG GT Coupe',
            'AMG GT Roadster',
            'AMG GT 4-Door',
            'MINI',
            'MINI 4-Door',
            'MINI Cabrio',
            'CLUBMAN',
            'COUNTRYMAN',
            'MINI JOHN COOPER WORKS',
            '718 Boxster',
            '718 Cayman',
            '911',
            '911 Cabriolet',
            '911 Targa',
            '911 Turbo',
            '911 Turbo Cabriolet',
            '911 Turbo S',
            '911 Turbo S Cabriolet',
            'Taycan',
            'Taycan Cross Turismo',
            'Panamera',
            'Panamera Turbo S',
            'Macan',
            'Cayenne',
            'PHANTOM',
            'PHANTOM EXTENDED',
            'CULLINAN',
            'GHOST',
            'GHOST EXTENDED',
            'WRAITH',
            'DAWN',
            'Fabia',
            'Scala',
            'Octavia',
            'Superb',
            'Kamiq',
            'Karoq',
            'Kodiaq',
            'Enyaq iV',
            'Model S',
            'Model 3',
            'Model X',
            'Model Y',
            'Yaris',
            'GR Yaris',
            'Yaris Cross',
            'Corolla',
            'CH-R',
            'Camry',
            'GR Supra',
            'Prius',
            'Mirai',
            'RAV4',
            'Highlinder',
            'Land Cruiser',
            'Hilux',
            'Golf',
            'Golf Variant',
            'Passat',
            'Passat Alltrack',
            'T-cross',
            'Taigo',
            'T-Roc',
            'Tiguan',
            'Touareg',
            'Arteon',
            'ID3',
            'ID4',
            'Caddy',
            'XC40',
            'XC60',
            'XC90',
            'V60',
            'S90',
            'S60',
            'V90',
            'V60',
          ],
        },
        {
          name: 'year',
          title: 'Metai',
          items: [
            '2012',
            '2013',
            '2014',
            '2015',
            '2016',
            '2017',
            '2018',
            '2019',
            '2020',
            '2021',
          ],
        },
      ],
    };
  }

  @Get('categories/language/:language/parent/:key')
  @ApiHeader({ required: true, name: 'project-id' })
  @ApiResponse({ status: 200, type: ParentRo })
  @Auth(AuthGuardsEnum.CUSTOMER_PROJECT)
  async parent(
    @Param('language') language: string,
    @Param('key') key: string,
  ): Promise<ParentRo> {
    return await this.searchService.categoriesParent(language, key);
  }

  @Get('categories/language/:language/child/:key')
  @ApiHeader({ required: true, name: 'project-id' })
  @ApiResponse({ status: 200, type: ChildRo })
  @Auth(AuthGuardsEnum.CUSTOMER_PROJECT)
  async child(
    @Param('language') language: string,
    @Param('key') key: string,
  ): Promise<ChildRo> {
    return await this.searchService.categoriesChild(language, key);
  }
}
