export enum AuthGuardsEnum {
  CUSTOMER_PROJECT = 'CUSTOMER_PROJECT',
  CUSTOMER_JWT = 'CUSTOMER_JWT',
  CUSTOMER_LOCAL = 'CUSTOMER_LOCAL',
  USER_PROJECT = 'USER_PROJECT',
  USER_JWT = 'USER_JWT',
  USER_LOCAL = 'USER_LOCAL',
}
